version: '2.0'

volumes:
  keycloak-app-db:

networks:
  navexdev:
    external:
      name: navexdev

services:
  keycloak-app:
    container_name: keycloak-app
    depends_on:
      - keycloak-app-db
    environment:
      NEW_RELIC_APP_NAME: keycloak (dev)
      NEW_RELIC_AGENT_ENABLED: 'false'
      NEW_RELIC_LICENSE_KEY: 'fake'
      DB_ADDR: keycloak-app-db
      DB_DATABASE: keycloak
      DB_PASSWORD: keycloak
      DB_PORT: '5432'
      DB_USER: keycloak
      DB_VENDOR: postgres
    ports:
      - '8443:8443'
      - '9990:9990'
    build:
      context: ./build/app
    image: navex/keycloak:11.0.3
    links:
      - keycloak-app-db
    networks:
      navexdev:
    restart: always
    volumes:
      - ./import/variants/keycloak-app:/import/variants/keycloak-app:rw
    entrypoint:
      - /opt/jboss/tools/start.sh
      - "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/import/variants/keycloak-app -Djboss.bind.address.management=0.0.0.0"

  keycloak-app-db:
    container_name: keycloak-app-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
    expose:
      - '5432'
    image: postgres:11.5
    networks:
      navexdev:
    restart: always
    volumes:
      - keycloak-app-db:/var/lib/postgresql/data:rw