version: '2.0'

volumes:
  db:

networks:
  keycloak:

services:
  app:
    container_name: keycloak-app
    depends_on:
      - db
    environment:
      NEW_RELIC_APP_NAME: keycloak (dev)
      NEW_RELIC_AGENT_ENABLED: 'true'
      NEW_RELIC_LICENSE_KEY: 'fake'
      #JAVA_OPTS: -javaagent:/opt/newrelic/newrelic.jar -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_PASSWORD: keycloak
      DB_PORT: '5432'
      DB_USER: keycloak
      DB_VENDOR: postgres
    ports:
      - '8443:8443'
      - '9990:9990'
    build:
      context: ./build/app
    image: navex/keycloak:8.0.2
    links:
      - db
    networks:
      keycloak:
    restart: always
    volumes:
      - ./import:/import:rw
    entrypoint:
      - /opt/jboss/tools/start.sh
      - "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/import -Djboss.bind.address.management=0.0.0.0"

  db:
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
    expose:
      - '5432'
    image: postgres:11.5
    networks:
      keycloak:
    restart: always
    volumes:
      - db:/var/lib/postgresql/data:rw
