AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Authorizer for securing APIs.

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W3002
        - I3042

Parameters:
  KCBaseUrl:
    Type: String
    Default: "*.keycloak.devlocal.navex-pe.com:8443"
  Auth0Domain:
    Type: String
    Default: "auth0.test.navex-dev.com"
  LayerName:
    Type: String
    Default: oidc-endpoint-authorizer-nodejs
  SingleDomain:
    Type: String
    Default: "envoy.navex-dev.com"

Outputs:
  CustomOidcAuthorizerLambdaName:
    Value: !Ref CustomOidcAuthorizerLambda
  ApiGatewayAuthorizerRole:
    Value: !Ref ApiGatewayAuthorizerRole
  LayerName:
    Value: !Ref LayerName
  LayerArn:
    Value: !GetAtt LayerArnSetSsm.Value

Resources:
  CustomOidcAuthorizerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Code: ./lambdas/oidc-custom-authorizer/output/
      Handler: index.handler
      Description: Authorize Endpoints for KeyCloak
      Environment:
        Variables:
          JWKS_URI: !Sub https://${KCBaseUrl}/auth/realms/navex/protocol/openid-connect/certs
          AUTH0_JWKS: !Sub https://${Auth0Domain}/.well-known/jwks.json
          ASM_JWKS: !Sub https://*.${SingleDomain}/authorization/jwks
      MemorySize: 512
      Runtime: nodejs18.x
      Timeout: 30
      Layers:
        - !GetAtt LayerArnSetSsm.Value

  CustomOidcAuthorizerLambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CustomOidcAuthorizerLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*"
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ApiGatewayAuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: "apigateway.amazonaws.com"
            Action: sts:AssumeRole
      Policies: 
        - PolicyName: "InvokeAuthorizerFunction"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                Resource: !GetAtt CustomOidcAuthorizerLambda.Arn
  
  AuthorizerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs18.x
        - nodejs16.x
      ContentUri: ./lambdas/oidc-authorizer-layer/output/
      LayerName: !Ref LayerName
      RetentionPolicy: Retain

  LayerArnSetSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /oidc-auth/layers/${LayerName}/arn
      Description: !Sub Amazon Resource Name of the ${LayerName} lambda layer.
      Type: String
      Value: !Ref AuthorizerLayer