@realm = navex
@client_id = appshell-api
@client_secret = 3ed2c99a-3a36-4432-8411-e35a315ae49a
@host = {{hostname}}:{{port}}
@accessToken = {{login.response.body.$.access_token}}

# @name login
POST /auth/realms/master/protocol/openid-connect/token HTTP/1.1
Host: {{host}}
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{client_id}} {{client_secret}}

grant_type=client_credentials