@realm = navex
@flowAlias = browser
@host = {{hostname}}:{{port}}
@accessToken = {{login.response.body.$.access_token}}

# @name login
POST /auth/realms/master/protocol/openid-connect/token HTTP/1.1
Host: {{host}}
Content-Type: application/x-www-form-urlencoded

username={{adminUsername}}&password={{adminPassword}}&client_id=admin-cli&grant_type=password

###

# @name getAuthenticationFlowExecutions
GET /auth/admin/realms/{{realm}}/authentication/flows/{{flowAlias}}/executions HTTP/1.1
Host: {{host}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}