version: 0.2

env:
  parameter-store:
    DockerhubUsername: /codebuild/dockerhub/username
    DockerhubPassword: /codebuild/dockerhub/password

phases:
  install:
    runtime-versions:
      python: 3.x
      nodejs: 18
    commands:
      - pip install --upgrade cfn-lint
  pre_build:
    commands:
      - echo $DockerhubPassword | docker login --username $DockerhubUsername --password-stdin
      - cd ./lambdas/oidc-authorizer-layer && npm install-ci-test && cd -
  build:
    commands:
      - echo Running cfn-lint to validate cfn templates
      - cfn-lint --version
      - cfn-lint --include-checks I -t template.yml
      - cfn-lint --include-checks I -t template.authorizer.yml
      - echo Building the Docker image... 
      - docker build -t navex/keycloak:pr ./build/app

