version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
      - cd ./lambdas/oidc-custom-authorizer && npm install-ci-test && cd -
      - cd ./lambdas/oidc-authorizer-layer && npm install-ci-test && cd -
  build:
    commands:
      - cd ./lambdas/oidc-authorizer-layer && npm run bundle && cd -
      - cd ./lambdas/oidc-custom-authorizer && npm run bundle && cd -
      - aws cloudformation package --template template.authorizer.yml --s3-bucket $S3_BUCKET --s3-prefix $S3_PREFIX --output-template auth.packaged.yml
artifacts:
  type: zip
  files:
    - auth.packaged.yml