version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install --upgrade awscli
      - cd lambdas/kc-api-proxy && pip install -r requirements.txt -t ./ && cd -
  build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --s3-prefix $S3_PREFIX --output-template app.packaged.yml
artifacts:
  type: zip
  files:
    - app.packaged.yml