AWSTemplateFormatVersion: 2010-09-09

Description: >
  Pipeline for unstable keycloak deployments
Parameters:
  ProjectName:
    Type: String
    Default: keycloak
  GitHubOwner:
    Type: String
    Default: tnwinc
  GitHubRepo:
    Type: String
    Default: platform-auth-keycloak
  GitHubBranch:
    Type: String
    Default: develop
  GitHubToken:
    Type: String
    NoEcho: true
  RegionalPackageStackName:
    Type: String
  # DevAccountId:
  #   Type: String
  #   Default: "552242929734"
  IntegrationAccountId:
    Type: String
    Default: "455920928861"

Resources:

  KCCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: "navex-codebuild"
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/navex-pipeline"
      Description: Builds the keycloak project
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: aws-inf/buildspec.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        Type: LINUX_CONTAINER

  KCPRCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: "navex-codebuild"
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitHubOwner}/${GitHubRepo}"
        BuildSpec: aws-inf/buildspec.yml
        GitCloneDepth: 1
        ReportBuildStatus: true
      Triggers:
        Webhook: true
        FilterGroups:
          - 
            - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
            - Type: BASE_REF
              Pattern: !Sub "^refs/heads/${GitHubBranch}$"
              ExcludeMatchedPattern: false

  TransformCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: "navex-codebuild"
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/navex-pipeline"
      Description: Transforms / merges dc artifacts into template-configuration.json
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: app/aws-inf/buildspec.transform.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        Type: LINUX_CONTAINER   

  PipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubToken
      Filters:
        - 
          JsonPath: "$.ref"
          MatchEquals: !Sub "refs/heads/${GitHubBranch}"
      TargetPipeline: !Ref Pipeline
      TargetAction: App
      Name: !Ref AWS::StackName
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${GitHubRepo}-${GitHubBranch}
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/navex-codepipeline
      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !Sub navex-artifacts-${AWS::AccountId}-us-east-1
            EncryptionKey: 
              Id: !Sub "arn:aws:kms:us-east-1:${AWS::AccountId}:alias/navex-pipeline"
              Type: KMS
        - Region: us-west-2
          ArtifactStore:
            Type: S3
            Location: !Sub navex-artifacts-${AWS::AccountId}-us-west-2
            EncryptionKey: 
              Id: !Sub "arn:aws:kms:us-west-2:${AWS::AccountId}:alias/navex-pipeline"
              Type: KMS
      Stages:
        - Name: Source
          Actions:
            - Name: App
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: App
              RunOrder: 1
        - Name: Build
          Actions:
            - 
              Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref KCCodeBuild
              InputArtifacts:
                - Name: App
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
            - 
              Name: PackageUsWest2
              Region: us-west-2
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Sub ${RegionalPackageStackName}-${ProjectName}
              InputArtifacts:
                - Name: App
              OutputArtifacts:
                - Name: PackageUsWest2
              RunOrder: 1
            -
              Name: PutProjVersion
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: "1"
                Provider: Lambda
              Configuration:
                FunctionName: CPPutProjectVersion
                UserParameters: |
                  {
                    "DeploySpecFile": "App::aws-inf/deployspec.json",
                    "OutputFile": "build-record.json"
                  }
              InputArtifacts:
                - Name: App
              OutputArtifacts:
                - Name: ProjectVersion
              RunOrder: 2
        - 
          Name: IntegrationAccount
          Actions:
            - 
              Name: GetDcArt_Wobbly
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: "1"
                Provider: Lambda
              Configuration:
                FunctionName: CPGetDCArtFromBuildInfo
                UserParameters: !Sub |
                  {
                    "SourceProjectId": "${ProjectName}_navexint_us-west-2",
                    "DeploymentContext": "wobbly",
                    "BuildInfoFile": "ProjectVersion::build-record.json"
                  }
              InputArtifacts:
                - Name: ProjectVersion
              OutputArtifacts:
                - Name: GetDcArt_Wobbly
              RunOrder: 1
            -
              Name: MergeArtifacts_Wobbly
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: "1"
                Provider: Lambda
              Configuration:
                FunctionName: CPMergeArtifacts
                UserParameters: |
                  {
                    "ArtifactPrefixMap":{
                      "ProjectVersion": "build_info",
                      "GetDcArt_Wobbly": "dc_art",
                      "App": "app"
                    }
                  }
              InputArtifacts:
                - Name: ProjectVersion
                - Name: GetDcArt_Wobbly
                - Name: App
              OutputArtifacts:
                - Name: MergeArtifacts_Wobbly
              RunOrder: 2
            - 
              Name: Transform_Wobbly
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref TransformCodeBuildProject
              InputArtifacts:
                - Name: MergeArtifacts_Wobbly
              OutputArtifacts:
                - Name: Transform_Wobbly
              RunOrder: 3
            - 
              Name: FinalizedCfnConfig_Wobbly
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: "1"
                Provider: Lambda
              Configuration:
                FunctionName: CPUpdateJsonFile
                UserParameters: |
                  {
                    "JsonFiles": [
                      "BuildOutput::template-configuration.json", 
                      "Transform_Wobbly::template-configuration.json" 
                    ],
                    "Json": {
                      "Parameters": {
                        "Subdomain": "id3.wobbly",
                        "DnsHostedZone": "navex-int.com",
                        "Stage": "Development"
                      },
                      "Tags": {"navex:deploy:context": "wobbly"} 
                    },
                    "OutputFile": "template-configuration.json"
                  }
              InputArtifacts:
                - Name: BuildOutput
                - Name: Transform_Wobbly
              OutputArtifacts:
                - Name: FinalizedCfnConfig_Wobbly
              RunOrder: 4
            - 
              Name: CfnDeploy_Wobbly
              Region: us-west-2
              RoleArn: !Sub arn:aws:iam::${IntegrationAccountId}:role/navex-codepipelineassume
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !Sub arn:aws:iam::${IntegrationAccountId}:role/navex-deploymentservice
                StackName: !Sub ${ProjectName}-wobbly
                TemplatePath: "PackageUsWest2::app.packaged.yml"
                TemplateConfiguration: "FinalizedCfnConfig_Wobbly::template-configuration.json"
                OutputFileName: stack-outputs.json
              InputArtifacts:
                - Name: PackageUsWest2
                - Name: FinalizedCfnConfig_Wobbly
              OutputArtifacts:
                - Name: CfnDeploy_Wobbly
              RunOrder: 5
            -
              Name: ConfigUpload_Wobbly          
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: "1"
                Provider: Lambda
              InputArtifacts:
                - Name: Transform_Wobbly
                - Name: CfnDeploy_Wobbly
              Configuration:
                FunctionName: CPS3Deploy
                UserParameters: !Sub |
                  {
                    "S3BucketName": "CfnDeploy_Wobbly::stack-outputs.json:ConfigBucket",
                    "BaseDirectory": "transformed-import",
                    "ExcludeArtifactsFromUpload": ["CfnDeploy_Wobbly"],
                    "AccountId": "${IntegrationAccountId}",
                    "Region": "us-west-2"
                  }
              RunOrder: 6
            -
              Name: ImportConfig_Wobbly
              RunOrder: 7
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: CPInvokeLambda2
                UserParameters: !Sub |
                  {
                    "FunctionName": "CfnDeploy_Wobbly::stack-outputs.json:CpConfigImportLambdaArn",
                    "Payload": "{}",
                    "AccountId": "${IntegrationAccountId}",
                    "Region": "us-west-2",
                    "ParseResponse": true
                  }
              InputArtifacts:
                - Name: CfnDeploy_Wobbly
            - 
              Name: PublishDeployment_Wobbly
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: "1"
                Provider: Lambda
              Configuration:
                FunctionName: CPSetDeploymentContext
                UserParameters: !Sub |
                  {
                    "ProjectId": "${ProjectName}_navexint_us-west-2",
                    "BuildInfoFile": "ProjectVersion::build-record.json",
                    "DeploymentContext": "wobbly",
                    "JsonArtifactFiles": ["CfnDeploy_Wobbly::stack-outputs.json"]
                  }
              InputArtifacts:
                - Name: ProjectVersion
                - Name: CfnDeploy_Wobbly              
              RunOrder: 8